import clear_day from '../weather-svgs/clear-day.svg'
import clear_night from '../weather-svgs/clear-night.svg'
import partly_cloudy_day from '../weather-svgs/partly-cloudy-day.svg'
import partly_cloudy_night from '../weather-svgs/partly-cloudy-night.svg'
import cloudy from '../weather-svgs/cloudy.svg'
import overcast from '../weather-svgs/overcast.svg'
import fog from '../weather-svgs/fog.svg'
import drizzle from '../weather-svgs/drizzle.svg'
import raindrop from '../weather-svgs/raindrop.svg'
import rain from '../weather-svgs/rain.svg'
import sleet from '../weather-svgs/sleet.svg'
import snowflake from '../weather-svgs/snowflake.svg'
import snow from '../weather-svgs/snow.svg'
import thunderstorms from '../weather-svgs/thunderstorms.svg'

export var WMOCodeToSVG = {
  0:clear_day,
  1:clear_day,
  2:partly_cloudy_day,
  3:cloudy,
  45:fog,
  48:fog,
  51:drizzle,
  53:drizzle,
  55:drizzle,
  56:drizzle,
  57:drizzle,
  61:raindrop,
  63:rain,
  65:rain,
  66:sleet,
  67:sleet,
  71:snowflake,
  73:snow,
  75:snow,
  77:snow,
  80:rain,
  81:rain,
  82:rain,
  85:rain,
  86:rain,
  95:thunderstorms,
  96:thunderstorms,
  99:thunderstorms,
  100:clear_night,
  101:clear_night,
  102:partly_cloudy_night,
  103:overcast,
  145:fog,
  148:fog,
  151:drizzle,
  153:drizzle,
  155:drizzle,
  156:drizzle,
  157:drizzle,
  161:raindrop,
  163:rain,
  165:rain,
  166:sleet,
  167:sleet,
  171:snowflake,
  173:snow,
  175:snow,
  177:snow,
  180:rain,
  181:rain,
  182:rain,
  185:rain,
  186:rain,
  195:thunderstorms,
  196:thunderstorms,
  199:thunderstorms,
}
export var wmoCodeInterpretation = {

    0: "Clear sky",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Overcast",
    4: "Visibility reduced by smoke",
    5: "Haze",
    6: "Widespread dust in the air",
    7: "Dust or sand raised by wind",
    8: "Well-developed dust or sand whirl(s)",
    9: "Duststorm or sandstorm",
    10: "Mist",
    11: "Shallow fog",
    12: "Continuous shallow fog",
    13: "Lightning visible, no thunder",
    14: "Precipitation not reaching ground",
    15: "Distant precipitation",
    16: "Nearby precipitation",
    17: "Thunderstorm, no precipitation",
    18: "Squalls",
    19: "Funnel cloud(s)",
    20: "Drizzle or snow grains",
    21: "Rain",
    22: "Snow",
    23: "Rain and snow or ice pellets",
    24: "Freezing drizzle or freezing rain",
    25: "Rain shower(s)",
    26: "Snow shower(s)",
    27: "Hail shower(s)",
    28: "Fog or ice fog",
    29: "Thunderstorm",
    30: "Decreasing slight/moderate duststorm",
    31: "No change in slight/moderate duststorm",
    32: "Increasing slight/moderate duststorm",
    33: "Decreasing severe duststorm",
    34: "No change in severe duststorm",
    35: "Increasing severe duststorm",
    36: "Slight/moderate low blowing snow",
    37: "Heavy low drifting snow",
    38: "Slight/moderate high blowing snow",
    39: "Heavy high drifting snow",
    40: "Distant fog or ice fog",
    41: "Fog patches",
    42: "Thinning fog, sky visible",
    43: "Thinning fog, sky invisible",
    44: "No change in fog, sky visible",
    45: "No change in fog, sky invisible",
    46: "Thickening fog, sky visible",
    47: "Thickening fog, sky invisible",
    48: "Fog depositing rime, sky visible",
    49: "Fog depositing rime, sky invisible",
    50: "Intermittent slight drizzle",
    51: "Continuous slight drizzle",
    52: "Intermittent moderate drizzle",
    53: "Continuous moderate drizzle",
    54: "Intermittent heavy drizzle",
    55: "Continuous heavy drizzle",
    56: "Slight freezing drizzle",
    57: "Moderate/heavy freezing drizzle",
    58: "Slight drizzle and rain",
    59: "Moderate/heavy drizzle and rain",
    60: "Intermittent slight rain",
    61: "Continuous slight rain",
    62: "Intermittent moderate rain",
    63: "Continuous moderate rain",
    64: "Intermittent heavy rain",
    65: "Continuous heavy rain",
    66: "Slight freezing rain",
    67: "Moderate/heavy freezing rain",
    68: "Slight rain or drizzle and snow",
    69: "Moderate/heavy rain or drizzle and snow",
    70: "Intermittent slight snow",
    71: "Continuous slight snow",
    72: "Intermittent moderate snow",
    73: "Continuous moderate snow",
    74: "Intermittent heavy snow",
    75: "Continuous heavy snow",
    76: "Diamond dust",
    77: "Snow grains",
    78: "Isolated star-like snow crystals",
    79: "Ice pellets",
    80: "Slight rain shower(s)",
    81: "Moderate/heavy rain shower(s)",
    82: "Violent rain shower(s)",
    83: "Slight rain and snow shower(s)",
    84: "Moderate/heavy rain and snow shower(s)",
    85: "Slight snow shower(s)",
    86: "Moderate/heavy snow shower(s)",
    87: "Slight snow pellets or small hail shower(s)",
    88: "Moderate/heavy snow pellets or small hail shower(s)",
    89: "Hail shower(s), no thunder",
    90: "Slight rain, not at observation time",
    91: "Moderate rain, not at observation time",
    92: "Heavy rain, not at observation time",
    93: "Slight snow, not at observation time",
    94: "Moderate snow, not at observation time",
    95: "Heavy snow, not at observation time",
    96: "Slight drizzle, not at observation time",
    97: "Moderate drizzle, not at observation time",
    98: "Heavy drizzle, not at observation time",
    99: "Thunderstorm, not at observation time",

  };

export var WMOCodeText = {

  0:"Clear Sky",
  1:"Mainly Clear",
  2:"Partly Cloudy",
  3:"Overcast",
  45:"Fog", 
  48:"Depositing Rime Fog", 
  51:"Light Drizzle", 
  53:"Moderate Drizzle", 
  55:"Dense Drizzle", 
  56:"Light Freezing Drizzle", 
  57:"Dense Freezing Drizzle",
  61:"Slight Rain", 
  63:"Moderate Rain",
  65:"Heavy Rain", 
  66:"Light Freezing Rain", 
  67:"Heavy Freezing Rain", 
  71:"Slight Snow Fall", 
  73:"Moderate Snow Fall", 
  75:"Heavy Snow Fall",  
  77:"Snow Grains", 
  80:"Slight Rain Showers",
  81:"Moderate Rain Showers",
  82:"Violent Rain Showers",
  85:"Slight Snow Showers",
  86:"Heavy Snow Showers",
  95:"Thunderstorm",
  96:"Thunderstorm With Slight Hail",
  99:"Thunderstorm With Heavy Hail",

}
export var WMOCodeToSVG_ = {
  0:"clear_day",
  1:"clear_day",
  2:"partly_cloudy_day",
  3:"overcast",
  45:"fog",
  48:"fog",
  51:"drizzle",
  53:"drizzle",
  55:"drizzle",
  56:"drizzle",
  57:"drizzle",
  61:"raindrop",
  63:"rain",
  65:"rain",
  66:"sleet",
  67:"sleet",
  71:"snowflake",
  73:"snow",
  75:"snow",
  77:"snow",
  80:"rain",
  81:"rain",
  82:"rain",
  85:"rain",
  86:"rain",
  95:"thunderstorm",
  96:"thunderstorm",
  99:"thunderstorm"
}
//   0	Clear sky
// 1, 2, 3	Mainly clear, partly cloudy, and overcast
// 45, 48	Fog and depositing rime fog
// 51, 53, 55	Drizzle: Light, moderate, and dense intensity
// 56, 57	Freezing Drizzle: Light and dense intensity
// 61, 63, 65	Rain: Slight, moderate and heavy intensity
// 66, 67	Freezing Rain: Light and heavy intensity
// 71, 73, 75	Snow fall: Slight, moderate, and heavy intensity
// 77	Snow grains
// 80, 81, 82	Rain showers: Slight, moderate, and violent
// 85, 86	Snow showers slight and heavy
// 95 *	Thunderstorm: Slight or moderate
// 96, 99 *	Thunderstorm with slight and heavy hail

  // 0: clear day 0
  // 1: clear night 
  // 2: cloudy 1,6  
  // 3: fog 3,4,5
  // 4: fog day,
  // 5: fog night, 
  // 6: hail, 
  // 7: lightning bolt, 
  // 8: mist,
  // 9: overcast,
  // 10: overcast day,
  // 11: overcast night, 
  // 12: partly cloudy day,
  // 13: partly cloudy night,
  // 14: partly cloudy day rain,
  // 15: partly cloudy day snow,
  // 16: partly cloud night rain,
  // 17: partly cloudy night snow,
  // 18: rain,
  // 19: raindrop,
  // 20: sleet,
  // 21: snow, 
  // 22: snowflake,
  // 23: thunderstorms,
  // 24: thunderstorms night,
  // 25: thunderstorms night rain,
  // 26: thunderstorms night snow, 
  // 27: thunderstorms rain,
  // 28: thunderstorms snow,
  // 29: wind

  
  